# Generated by Django 3.0.6 on 2020-05-11 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swickapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='restaurant_phone_number',
        ),
    ]
