# Generated by Django 3.0.7 on 2020-09-28 22:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import swickapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('swickapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('token', models.CharField(default=swickapp.models.generate_token, max_length=40)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('accepted', models.BooleanField(default=False)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swickapp.Restaurant')),
            ],
        ),
    ]
