# Generated by Django 3.0.7 on 2020-09-29 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swickapp', '0002_serverrequest'),
        ('swickapp', '0002_auto_20200926_0007'),
    ]

    operations = [
    ]
