# Generated by Django 3.0.6 on 2020-05-31 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swickapp', '0003_auto_20200526_0344'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='category',
            field=models.CharField(default='Entrees', max_length=256, verbose_name='category (ex: appetizers)'),
            preserve_default=False,
        ),
    ]
