# Generated by Django 3.0.7 on 2020-09-30 17:07

from django.db import migrations, models
import swickapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('swickapp', '0003_merge_20200929_0037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='chef',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_completed',
        ),
        migrations.RemoveField(
            model_name='order',
            name='server',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('COOKING', 'Cooking'), ('SENDING', 'Sending'), ('COMPLETE', 'Complete')], default='COOKING', max_length=16),
        ),
        migrations.AlterField(
            model_name='customer',
            name='stripe_cust_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PROCESSING', 'Payment processing'), ('ACTIVE', 'Active'), ('COMPLETE', 'Complete')], default='PROCESSING', max_length=16),
        ),
    ]
