# Generated by Django 3.0.6 on 2020-08-12 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swickapp', '0004_meal_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='category',
            field=models.CharField(max_length=256, verbose_name='category (ex. Appetizers)'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='image',
            field=models.FileField(upload_to='', verbose_name='restaurant image'),
        ),
    ]
