# Generated by Django 3.0.6 on 2020-05-12 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swickapp', '0004_meal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
