# Generated by Django 3.0.7 on 2020-10-03 00:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('swickapp', '0004_auto_20200930_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swickapp.Restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('table', models.IntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swickapp.Customer')),
                ('request_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swickapp.RequestOption')),
            ],
        ),
    ]
