# Generated by Django 3.0.7 on 2020-10-03 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swickapp', '0005_request_requestoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
