# Generated by Django 3.0.6 on 2020-05-12 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swickapp', '0007_ordermeal'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='chef',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chef', to='swickapp.Server'),
        ),
        migrations.AlterField(
            model_name='order',
            name='server',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='server', to='swickapp.Server'),
        ),
    ]
