# Generated by Django 3.0.7 on 2020-10-04 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swickapp', '0007_auto_20201004_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='restaurant image'),
        ),
    ]
