# Generated by Django 3.0.7 on 2020-10-06 03:38

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swickapp', '0008_auto_20201004_2351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='tax',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='tax',
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='default_sales_tax',
            field=models.DecimalField(decimal_places=3, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='default sales tax (%)'),
        ),
        migrations.CreateModel(
            name='TaxCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('tax', models.DecimalField(decimal_places=3, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Sales tax (%)')),
                ('restaurant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='swickapp.Restaurant')),
            ],
            options={
                'unique_together': {('restaurant', 'name')},
            },
        ),
        migrations.AddField(
            model_name='meal',
            name='tax_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='swickapp.TaxCategory', verbose_name='Sales tax category'),
        ),
    ]
