# Generated by Django 3.0.7 on 2020-10-07 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swickapp', '0009_auto_20201006_0338'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stripe_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
