# Generated by Django 3.0.6 on 2020-05-12 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swickapp', '0009_auto_20200512_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='restaurant_address',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='restaurant_image',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='restaurant_name',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='address',
            field=models.CharField(default='street', max_length=256, verbose_name='restaurant address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(default='blank.jpg', upload_to='', verbose_name='restaurant image (display in app)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='name',
            field=models.CharField(default='bob', max_length=256, verbose_name='restaurant_name'),
            preserve_default=False,
        ),
    ]
