# Generated by Django 3.0.7 on 2020-10-21 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swickapp', '0010_order_stripe_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tip',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tip_stripe_payment_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
