# Generated by Django 3.0.6 on 2020-05-12 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swickapp', '0010_auto_20200512_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='restaurant image (displayed in app)'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(max_length=256, verbose_name='restaurant name'),
        ),
    ]
