# Generated by Django 3.0.6 on 2020-05-13 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swickapp', '0011_auto_20200512_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image (please use 16:9 aspect ratio)'),
        ),
    ]
