# Generated by Django 3.0.6 on 2020-05-13 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swickapp', '0012_auto_20200513_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image (displayed as square)'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='restaurant image (displayed with 16:9 aspect ratio)'),
        ),
    ]
