# Generated by Django 3.0.6 on 2020-05-17 07:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swickapp', '0017_auto_20200516_0038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('min', models.IntegerField(verbose_name='minimum selectable options')),
                ('max', models.IntegerField(verbose_name='maximum selectable options')),
                ('options', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), size=None)),
                ('price_additions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=256, null=True), size=None)),
            ],
        ),
    ]
