# Generated by Django 3.0.6 on 2020-05-17 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swickapp', '0019_auto_20200517_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='customization',
            name='meal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='swickapp.Meal'),
            preserve_default=False,
        ),
    ]
