# Generated by Django 3.0.6 on 2020-05-17 08:17

from decimal import Decimal
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swickapp', '0020_customization_meal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customization',
            name='price_additions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]), size=2),
        ),
    ]
