# Generated by Django 3.0.6 on 2020-05-17 21:11

from decimal import Decimal
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swickapp', '0021_auto_20200517_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customization',
            name='options',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256, verbose_name='options (separate with commas)'), size=None),
        ),
        migrations.AlterField(
            model_name='customization',
            name='price_additions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='price additions (separate with commas, insert 0 if no addition)'), size=None),
        ),
    ]
