# Generated by Django 3.0.6 on 2020-05-17 21:39

from decimal import Decimal
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swickapp', '0023_auto_20200517_2113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customization',
            old_name='name',
            new_name='customization_name',
        ),
        migrations.RenameField(
            model_name='meal',
            old_name='name',
            new_name='meal_name',
        ),
        migrations.AlterField(
            model_name='customization',
            name='options',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), size=None, verbose_name='options (separate with commas)'),
        ),
        migrations.AlterField(
            model_name='customization',
            name='price_additions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]), size=None, verbose_name='price additions (separate with commas, insert 0 if no addition)'),
        ),
    ]
