# Generated by Django 3.0.6 on 2020-05-17 22:23

from decimal import Decimal
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swickapp', '0024_auto_20200517_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customization',
            name='options',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), size=None, verbose_name='options (one on each line)'),
        ),
        migrations.AlterField(
            model_name='customization',
            name='price_additions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0'))]), size=None, verbose_name='price additions (one on each line, insert 0 if no addition)'),
        ),
    ]
