# Generated by Django 3.0.6 on 2020-05-18 06:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swickapp', '0025_auto_20200517_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customization',
            name='max',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='maximum selectable options'),
        ),
        migrations.AlterField(
            model_name='customization',
            name='min',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='minimum selectable options'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='description',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
